export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ADD_EXPERIENCE= "ADD_EXPERIENCE";
export const DELETE_EXPERIENCE= "DELETE_EXPERIENCE";
export const ADD_EDUCATION= "ADD_EDUCATION";
export const DELETE_EDUCATION= "DELETE_EDUCATION";
export const GET_ALL_PROFILES= "GET_ALL_PROFILES";
export const GET_REPOS= "GET_REPOS";
export const LOADER= "LOADER";
export const GIT_HUB_LOADER= "GIT_HUB_LOADER";


export const FETCHING_EXPERIENCE="FETCHING_EXPERIENCE";

export const GET_POST="GET_POST";
export const POST_LOADER = "POST_LOADER";


export const UPDATE_LIKE="UPDATE_LIKE";
export const REMOVE_LIKE="REMOVE_LIKE";
export const DELETE_POST="DELETE_POST";
export const ADD_POST="ADD_POST";
export const GET_SINGLE_POST="GET_SINGLE_POST";
export const ADD_COMMENT="ADD_COMMENT";
export const REMOVE_COMMENT="REMOVE_COMMENT";
